version: '2.29.4'

services:
  app:
    image: javademo
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/localspringbootdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root


    depends_on:
      - db

  db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: localspringbootdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - 3307:3306
